name: Software Composition Analysis

on: [pull_request]
#  push:
#    paths:
#      - pyproject.toml
#      - poetry.lock
#  schedule:
#    - cron: '0 0 * * 0'  # Midnight, Sunday

permissions:
  contents: read
  actions: write

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install CycloneDX CLI
        run: |
          curl -sSL https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64 -o /usr/local/bin/cyclonedx
          chmod +x /usr/local/bin/cyclonedx
          cyclonedx --version  # verify it runs

      - name: Generate CycloneDX SBOM
        run: |
          cyclonedx

      - uses: actions/upload-artifact@v4
        with:
          name: bom
          path: bom.json
          if-no-files-found: error

  sca:
    runs-on: ubuntu-latest
    needs: bom
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download SBOM
        uses: actions/download-artifact@v4
        with:
          name: bom

      - name: Run FOSSology analysis
        id: fossology
        uses: fossology/fossology-action@v1
        with:
          scan_mode: "scan-only-deps"
          scanners: |
            - nomos
            - ojo
            - copyright
          report_format: "SPDX_JSON"
          sbom_path: "bom.json"

      - name: Upload Scan Results Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: Fossology scan results
          path: results/