name: FOSSology License Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  fossology-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run FOSSology in Docker
      run: |
         docker run --rm \
         -v "${{ github.workspace }}":/repo \
         fossology/fossology-cli:latest \
         --mode cli --path /repo --output /repo/fossology-report.spdx

    - name: Upload SPDX report
      uses: actions/upload-artifact@v4
      with:
        name: fossology-spdx
        path: fossology-report.spdx
