name: FOSSology Scan via API

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  fossology-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Start FOSSology container
      run: |
        docker run -d --name fossology \
          -p 8081:80 fossology/fossology:latest
        sleep 30  # Give it time to initialize

    - name: Upload code for scanning
      run: |
        zip -r source.zip .
        curl -X POST "http://localhost/repo/api/v1/uploads" \
          -F "file=@source.zip" \
          -F "folder=default" \
          -F "public=true" \
          -u fossy:fossy

    - name: Stop container
      run: docker stop fossology
