name: License Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan-licenses:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python 3.10
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt-get update
        sudo apt-get install -y python3.10 python3.10-venv python3.10-distutils
        sudo ln -s /usr/bin/python3.10 /usr/local/bin/python3.10

    - name: Download ScanCode Toolkit
      run: |
        mkdir -p /tmp/tools
        cd /tmp/tools
        curl -L -o scancode-toolkit.tar.gz \
          https://github.com/aboutcode-org/scancode-toolkit/releases/download/v32.4.1/scancode-toolkit-v32.4.1_py3.10-linux.tar.gz
        tar -xzf scancode-toolkit.tar.gz
        mv scancode-toolkit-* scancode-toolkit

    - name: Run ScanCode
      run: |
        cd /tmp/tools/scancode-toolkit/ && ./configure
        ./scancode \
          --license \
          --copyright \
          --json-pp ${{ github.workspace }}/results.json ${{ github.workspace }}

    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: scancode-results
        path: results.json
